apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-shared-pv-system
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: analytics-cephfs-nfs
  mountOptions:
    - vers=4.1
    - proto=tcp
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.100.58.50
    path: /1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-shared-pvc
  namespace: analytics-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: analytics-cephfs-nfs
  volumeName: analytics-shared-pv-system
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-shared-pv-jobs
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: analytics-cephfs-nfs
  mountOptions:
    - vers=4.1
    - proto=tcp
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 10.100.58.50
    path: /1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-shared-pvc
  namespace: analytics-jobs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: analytics-cephfs-nfs
  volumeName: analytics-shared-pv-jobs
  resources:
    requests:
      storage: 200Gi
