apiVersion: v1
kind: Secret
metadata:
  name: analytics-postgres-secret
  namespace: analytics-system
type: Opaque
stringData:
  POSTGRES_DB: analytics
  POSTGRES_USER: analytics_user
  POSTGRES_PASSWORD: analytics_pass_2026
